# Generated by Django 3.0.5 on 2020-06-10 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('domacinstvo', '0002_auto_20200427_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaj',
            name='tip_dogadjaja',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='planer',
            name='mesec_za_prikaz',
            field=models.DateField(default=datetime.datetime(2020, 6, 10, 11, 2, 14, 371123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='planer',
            name='selektovan_datum',
            field=models.DateField(default=datetime.datetime(2020, 6, 10, 11, 2, 14, 371144, tzinfo=utc)),
        ),
    ]
